"""empty message

Revision ID: 2fa5a1972e87
Revises: 4f015e840304
Create Date: 2016-07-19 22:22:35.191206

"""

# revision identifiers, used by Alembic.
revision = '2fa5a1972e87'
down_revision = '4f015e840304'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
